#ifndef GAUSSIAN_FILTER_PLUGIN_GLOBAL_H
#define GAUSSIAN_FILTER_PLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GAUSSIAN_FILTER_PLUGIN_LIBRARY)
#  define GAUSSIAN_FILTER_PLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GAUSSIAN_FILTER_PLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GAUSSIAN_FILTER_PLUGIN_GLOBAL_H
